### ISSUE TITLE
[travis-ci] support specify some services

### ISSUE THREAD

**Issue by richardo2016** [fibjs-modules/ci#3]
sometimes we need to run test depending on some backend daemon services, such as `mysql`, `mongodb`, `redis`.

travis-ci support setup those services, in general [databases services](https://docs.travis-ci.com/user/database-setup/)

**Comment by ngot** [comment]
https://github.com/fibjs-modules/ci/pull/4

**Comment by ngot** [comment]
Landed  at @fibjs/ci@2.2.0
